# Generated by Django 5.0.7 on 2024-07-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_movie_rating_alter_movie_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.URLField(default='https://example.com', verbose_name='Ссылка'),
        ),
    ]
